sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t client-test -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true client-test npm run test -- --coverage
after_success:
  - docker build -t rohityadav007/multi-client ./client
  - docker build -t rohityadav007/multi-server ./server
  - docker build -t rohityadav007/multi-nginx ./nginx
  - docker build -t rohityadav007/multi-worker ./worker
  # login to docker using env variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rohityadav007/multi-client
  - docker push rohityadav007/multi-server
  - docker push rohityadav007/multi-nginx
  - docker push rohityadav007/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-multi"
  env: "Dockermulti-env"
  bucket_name: "elasticbeanstalk-eu-central-1-876515858155"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
